name: "Bug Report"
description: "Signaler un bug sur le site cto-de-lyon.fr"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré.
      placeholder: "Le bouton X ne fonctionne pas quand..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Les étapes pour reproduire le bug.
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Observer '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Ce qui devrait se passer.
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Autre
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: Appareil
      options:
        - Desktop
        - Mobile
        - Tablette
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran.
    validations:
      required: false
