name: "Feature Request"
description: "Proposer une amélioration ou une nouvelle fonctionnalité"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de proposer une amélioration pour le site.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décrivez la fonctionnalité ou l'amélioration souhaitée.
      placeholder: "Il serait utile de..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Pourquoi cette fonctionnalité serait utile ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Si vous avez une idée de solution, décrivez-la.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: Avez-vous envisagé d'autres approches ?
    validations:
      required: false
